package src;

public enum Provincia {
	TIERRA_DEL_FUEGO, SANTA_CRUZ,CHUBUT,RIO_NEGRO,NEUQUEN,LA_PAMPA,BUENOS_AIRES,
	CORDOBA,SAN_LUIS,ENTRE_RIOS,SANTA_FE,CORRIENTES,MISIONES,CHACO,FORMOSA,SANTIAGO_DEL_ESTERO,
	JUJUY,SALTA,TUCUMAN,CATAMARCA,LA_RIOJA,SAN_JUAN;
	
}
